package com.idavy.drtops.domain.location;

public enum LocationQualityReason {
    RECEIVE_DELAY, RECEIVE_DELAY_EXCEEDED, TERMINAL_TIME_AHEAD, TERMINAL_TIME_AHEAD_EXCEEDED,
    OUT_OF_ORDER, INVALID_COORDINATE, POSITION_INVALID, SPEED_WARNING, SPEED_EXCEEDED,
    IMPLIED_SPEED_EXCEEDED, OUTSIDE_SERVICE_AREA, OPTIONAL_FIELDS_MISSING, CONSECUTIVE_QUARANTINE
}
