package com.idavy.drtops.jtgateway.session;

public enum RegistrationRejection {
    NOT_PREPROVISIONED(1),
    TERMINAL_CODE_NOT_FOUND(1),
    TERMINAL_STATE_INVALID(1),
    TERMINAL_ALREADY_REGISTERED(1),
    TERMINAL_PHONE_MISMATCH(1),
    MANUFACTURER_MISMATCH(1),
    MODEL_MISMATCH(1),
    PROTOCOL_VERSION_MISMATCH(1),
    BINDING_MISSING(1),
    VEHICLE_IDENTIFIER_MISMATCH(1),
    REGISTRATION_VERIFY_BAD_REQUEST(1),
    REGISTRATION_VERIFY_UNAUTHORIZED(1),
    REGISTRATION_VERIFY_CONFLICT(1),
    REGISTRATION_VERIFY_UNAVAILABLE(1),
    REGISTRATION_COMPLETE_BAD_REQUEST(1),
    REGISTRATION_COMPLETE_UNAUTHORIZED(1),
    REGISTRATION_COMPLETE_CONFLICT(1),
    REGISTRATION_COMPLETE_UNAVAILABLE(1),
    REGISTRATION_TERMINAL_PHONE_EMPTY(1),
    REGISTRATION_MANUFACTURER_EMPTY(1),
    REGISTRATION_MODEL_EMPTY(1),
    REGISTRATION_TERMINAL_CODE_EMPTY(1),
    REGISTRATION_VEHICLE_IDENTIFIER_EMPTY(1),
    TERMINAL_SUSPENDED(2),
    IDENTITY_MISMATCH(2),
    BINDING_INACTIVE(3),
    MALFORMED_REGISTRATION(2);

    private final int protocolResult;

    RegistrationRejection(int protocolResult) {
        this.protocolResult = protocolResult;
    }

    public int protocolResult() {
        return protocolResult;
    }

    public static RegistrationRejection fromReasonCode(String reasonCode) {
        if (reasonCode == null) {
            return NOT_PREPROVISIONED;
        }
        return switch (reasonCode) {
            case "TERMINAL_CODE_NOT_FOUND" -> TERMINAL_CODE_NOT_FOUND;
            case "TERMINAL_STATE_INVALID" -> TERMINAL_STATE_INVALID;
            case "TERMINAL_ALREADY_REGISTERED" -> TERMINAL_ALREADY_REGISTERED;
            case "TERMINAL_PHONE_MISMATCH" -> TERMINAL_PHONE_MISMATCH;
            case "MANUFACTURER_MISMATCH" -> MANUFACTURER_MISMATCH;
            case "MODEL_MISMATCH" -> MODEL_MISMATCH;
            case "PROTOCOL_VERSION_MISMATCH" -> PROTOCOL_VERSION_MISMATCH;
            case "BINDING_MISSING" -> BINDING_MISSING;
            case "VEHICLE_IDENTIFIER_MISMATCH" -> VEHICLE_IDENTIFIER_MISMATCH;
            default -> NOT_PREPROVISIONED;
        };
    }
}
