package com.idavy.drtops.jtgateway.session;

public enum SessionAuditType {
    REGISTRATION_ACCEPTED,
    REGISTRATION_REJECTED,
    AUTHENTICATION_ACCEPTED,
    AUTHENTICATION_REJECTED,
    AUTHENTICATION_LOCKED,
    AUTHENTICATION_TIMEOUT,
    PRE_AUTH_MESSAGE_REJECTED,
    SESSION_IDENTITY_MISMATCH,
    SESSION_TAKEN_OVER,
    SESSION_OFFLINE
}
